
-- HereNow

CREATE SCHEMA IF NOT EXISTS hn AUTHORIZATION ekhoesadmin;
GRANT ALL PRIVILEGES ON SCHEMA hn TO ekhoesadmin;

DROP TABLE IF EXISTS hn.LIKES;
DROP TABLE IF EXISTS hn.SUBSCRIPTIONS;
DROP TABLE IF EXISTS hn.COMMENTS;
DROP TABLE IF EXISTS hn.CATEGORIES;
DROP TABLE IF EXISTS hn.HOTSPOTS;
DROP TABLE IF EXISTS hn.USERS;

-- Users
CREATE TABLE IF NOT EXISTS hn.users (
	id VARCHAR(100) PRIMARY KEY NOT NULL,
	email VARCHAR(100) UNIQUE,
	password VARCHAR(200),
	name VARCHAR(100),
	status VARCHAR(50) DEFAULT 'pending',
	last_access TIMESTAMP WITH TIME ZONE,
	created TIMESTAMP DEFAULT NOW(),
	updated TIMESTAMP DEFAULT NOW()
);

-- Hotspots
CREATE TABLE hn.HOTSPOTS (
	id VARCHAR(100) PRIMARY KEY NOT NULL,
	name VARCHAR(100),
	description VARCHAR(4000),
	owner VARCHAR(100),
	category VARCHAR(50),
	enabled bool,
	private bool default false,
	position geography(Point, 4326),
	start_time TIMESTAMP,
	end_time TIMESTAMP,
	created TIMESTAMP DEFAULT NOW(),
	updated TIMESTAMP DEFAULT NOW(),
	
	CONSTRAINT fk_user
		FOREIGN KEY (owner)
		REFERENCES hn.users(id)
		ON DELETE CASCADE
);

CREATE INDEX idx_hotspots_position
ON hn.HOTSPOTS
USING GIST (position);

-- Categories
CREATE TABLE hn.CATEGORIES (
	id VARCHAR(100) PRIMARY KEY NOT NULL,
	label VARCHAR(100),
	color VARCHAR(50)
);

insert into hn.CATEGORIES ("id", "label") values ('food', 'Food');
insert into hn.CATEGORIES ("id", "label") values ('sports', 'Sports');
insert into hn.CATEGORIES ("id", "label") values ('art', 'Art');
insert into hn.CATEGORIES ("id", "label") values ('music', 'Music');
insert into hn.CATEGORIES ("id", "label") values ('tech', 'Tech');
insert into hn.CATEGORIES ("id", "label") values ('fun', 'Fun');
insert into hn.CATEGORIES ("id", "label") values ('study', 'Study');
insert into hn.CATEGORIES ("id", "label") values ('work', 'Work');
insert into hn.CATEGORIES ("id", "label") values ('travel', 'Travel');
insert into hn.CATEGORIES ("id", "label") values ('culture', 'Culture');
insert into hn.CATEGORIES ("id", "label") values ('business', 'Business');
insert into hn.CATEGORIES ("id", "label") values ('commerce', 'Commerce');
insert into hn.CATEGORIES ("id", "label") values ('nature', 'Nature');
insert into hn.CATEGORIES ("id", "label") values ('danger', 'Danger');
insert into hn.CATEGORIES ("id", "label") values ('z_other', 'Other');

-- Likes
CREATE TABLE hn.LIKES (
	hotspot_id VARCHAR(100),
	user_id VARCHAR(100),
	created TIMESTAMP DEFAULT NOW(),

	CONSTRAINT fk_hotspot
		FOREIGN KEY (hotspot_id)
		REFERENCES hn.HOTSPOTS(id)
		ON DELETE CASCADE,

	CONSTRAINT fk_user
		FOREIGN KEY (user_id)
		REFERENCES hn.users(id)
		ON DELETE CASCADE
);

-- Subscriptions
CREATE TABLE hn.SUBSCRIPTIONS (
	hotspot_id VARCHAR(100),
	user_id VARCHAR(100),
	created TIMESTAMP DEFAULT NOW(),

	CONSTRAINT fk_hotspot
		FOREIGN KEY (hotspot_id)
		REFERENCES hn.HOTSPOTS(id)
		ON DELETE CASCADE,

	CONSTRAINT fk_user
		FOREIGN KEY (user_id)
		REFERENCES hn.users(id)
		ON DELETE CASCADE
);

-- Comments
CREATE TABLE hn.COMMENTS (
	id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	hotspot_id VARCHAR(100),
	user_id VARCHAR(100),
	message VARCHAR(200) NOT NULL,
	created TIMESTAMP DEFAULT NOW(),
	updated TIMESTAMP DEFAULT NOW(),

	CONSTRAINT fk_hotspot
		FOREIGN KEY (hotspot_id)
		REFERENCES hn.HOTSPOTS(id)
		ON DELETE CASCADE,

	CONSTRAINT fk_user
		FOREIGN KEY (user_id)
		REFERENCES hn.users(id)
		ON DELETE CASCADE
);

-- Grants
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA hn TO ekhoesadmin;


